### PR TITLE
Added support for Multi device

### PR DESCRIPTION
**Pull request by pravinraghul**
Addressing issue #4 & #5 

### Implemented
 - API's to read & write to multi device.
 - Added example "MulDevUsage".
 - Doesn't modify any previous API's.

### Not covered
 - API's don't support read or write different data types.

### Tested
- Connecting two devices, adding results of running "MulDevUsage" with two devices.

> ******* Writing ********
*** Writing to 50 ***
0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc, 0xde, 0xf0, 
*** Writing to 52 ***
0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc, 0xde, 0xf0, 
******* Reading ********
*** Reading from 50 ***
0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc, 0xde, 0xf0, 
*** Reading from 52 ***
0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc, 0xde, 0xf0,

### CODE REVIEW

**Comment by WifWaf** [comment]
Thanks for suggesting this.  If you're able to update your example using the library changes I uploaded so I can add your example, I would be greatly appreciated it

**Comment by WifWaf** [comment]
As a side note, adding the using address as an overload function does work, however, it doesn't support the inline functions.

Arduino also has conventions around how addresses are best passed. It's not always the most efficient but aims to keep things simple and predictable.

**Comment by pravinraghul** [comment]
Thanks for the changes you made in the 2.3.0, can we close this thread.


closes #5

**Comment by pravinraghul** [comment]
Will add the examples that you requested.

**Pull request closed without merging**
